### ISSUE TITLE
> 100 Records

### ISSUE THREAD

**Issue by joshreisner** [TappNetwork/laravel-airtable#12]
I'd like to get all records from my table, but I only get the first 100 when I do 

```
$results = Airtable::table('default')->get();
```

How do you recommend I get all records? Thanks

**Comment by swilla** [comment]
Airtable by can only return 100 rows at a time, you should get offsets back to make the next request. If you are having trouble I can try and provide a code sample.

**Comment by joshreisner** [comment]
Thanks, it'd be cool to get some documentation on what the proper way to do that would be with this library.

That said, I'll close this issue because I just wrote my own fetching algo that uses the offset.

**Comment by raoulwegat** [comment]
>  If you are having trouble I can try and provide a code sample.

@swilla Yes please. I've got the offset loop working but would like to know where the offset value  gets added to the Airtable call. Btw - I'm also using the where method.

**Comment by raoulwegat** [comment]
After all that, I finally figured it out. :-)

Code sample for anyone else wanting to use get() and offset.

`do {
	$query = "";

	if ($offset) {
		$query = $offset;
	}
	
	$response = Airtable::table('default')->where('Column Name', '>', '0')->get('?offset='.$query, '');

	if (isset($response['records'])) {
		$records = array_merge($response['records'], $records);
	}
	
	if (isset($response['offset'])) {
		$offset = $response['offset'];
		usleep(200000);
	} else {
		$offset = false;
	}

} while ($offset);`

**Comment by swilla** [comment]
This PR was merged recently that gets all records: https://github.com/TappNetwork/laravel-airtable/pull/21 does this help at all?

**Comment by joshreisner** [comment]
@swilla this looks awesome thank you!
