### ISSUE TITLE
Find by LIKE

### ISSUE THREAD

**Issue by andradedpg** [TappNetwork/laravel-airtable#20]
Hey!

Firstly, thank you! Works very well in my application. 

Would you think implements a where function to acceps like operators?
`$data = AirTable::table('table')->where('columnName','LIKE','%partOfText%')->get()`

Sounds good ? Let me know if you need help it. 

Best!

**Comment by swilla** [comment]
I think you need to use `filterByFormula` under the hood to make something like this happen. 

https://support.airtable.com/hc/en-us/articles/203255215-Formula-Field-Reference

Feel free to submit a PR with this functionality.
