### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by paul-siteway** [TappNetwork/laravel-airtable#23]
Do you plan to support Laravel 8?

**Comment by swilla** [comment]
https://github.com/TappNetwork/laravel-airtable/pull/24

**Comment by paul-siteway** [comment]
awesome!

**Comment by io238** [comment]
Laravel 8 requires Guzzle (`guzzlehttp/guzzle`) 7.0.1 or above - https://laravel.com/docs/8.x/upgrade#updating-dependencies
