### ISSUE TITLE
Support for Laravel 8

### ISSUE THREAD

**Issue by kaleidoscope-niraj** [TappNetwork/laravel-airtable#25]
I am trying to use it in Laravel 8 and it would be great if you could support it. And even lowering the guzzlehttp version to ~6.0 is not fixing it as 7.0.1 is the minimum requirement for Laravel 8.

> The requested package guzzlehttp/guzzle (locked at 7.0.1, required as ~6.0) is satisfiable by guzzlehttp/guzzle[7.0.1] but these conflict with your requirements or minimum-stability.

**Comment by swilla** [comment]
the latest version supports Laravel 8 and Guzzle 7 now.
