### ISSUE TITLE
Multiple where clauses

### ISSUE THREAD

**Issue by yassinebourakba** [TappNetwork/laravel-airtable#28]
The package doesn't support the use of multiple `where` clauses.

1. The following piece of code shouldn't rise an exception:
```
Airtable::table('products')
   ->where('name', 'product_name')
   ->where('category', 'product_category')
   ->get();
```
The `where` function in `Airtbale` class should return `$this`.

2. When i use `addFilter` functions instead of `where` the generated url in `getEndpointUrl` is wrong, it doesn't correctly support multiple filters:
```
Airtable::table('products')
   ->where('name', 'product_name')
   ->addFilter('category', '=', 'product_category')
   ->get();
```

I wanted to make a PR, fixed this simple but useful issue in a branch but couldn't push it

**Comment by swilla** [comment]
If you make a fork of the repo, then you can submit a PR, thanks for this feature!
