### ISSUE TITLE
[Feature Request] Update to PHP 8

### ISSUE THREAD

**Issue by Codex101** [TappNetwork/laravel-airtable#36]
I'm using the latest PHP: 8.0.2 and get this error when trying to install.

`Package tapp/laravel-airtable has a PHP requirement incompatible with your PHP version`

Any chance this package could be updated to PHP 8? 

Thank You

**Comment by swilla** [comment]
@Codex101 I created a PR for PHP 8 support.  I don't have time to test it right now so if you want to try it you can change your composer require to: 
```
"tapp/laravel-airtable": "dev-php8",
```

**Comment by swilla** [comment]
https://github.com/TappNetwork/laravel-airtable/releases/tag/v0.20
