### ISSUE TITLE
Can't get this to work

### ISSUE THREAD

**Issue by pastorryanhayden** [TappNetwork/laravel-airtable#4]
I've followed the installation instructions provided in the readme but when I try to access Airtable in a controller I get this error:

`Class 'App\Http\Controllers\Airtable' not found`

I've tried `use Tapp\Airtable;` and it's not finding that either.

I can confirm that `airtable.php` is in the app/config directory and that I have the right stuff in the .env file.

**Comment by swilla** [comment]
What version of Laravel are you running?  The facade should be auto-discovered: 

https://github.com/TappNetwork/laravel-airtables/blob/master/composer.json#L48-L53

You will just need to add the following at the top of the controller you are using it in: 

```
user Airtable;
```

If this does the trick I'll update the readme.

**Comment by dylanmichaelryan** [comment]
> What version of Laravel are you running? The facade should be auto-discovered:
> 
> https://github.com/TappNetwork/laravel-airtables/blob/master/composer.json#L48-L53
> 
> You will just need to add the following at the top of the controller you are using it in:
> 
> ```
> use Airtable;
> ```
> 
> If this does the trick I'll update the readme.

This helped me.
