### ISSUE TITLE
Non-static method Tapp\Airtable\Airtable::table()

### ISSUE THREAD

**Issue by jatniel** [TappNetwork/laravel-airtable#45]
_ErrorException_
Non-static method Tapp\Airtable\Airtable::table() should not be called statically

I have configured following your documentation and I get this error.

`$products = Airtable::table('Products')->get();
`

Version Laravel 8 / php 8.0

**Comment by swilla** [comment]
Are you using the facade or are you importing the whole namespace to the class? I also see you have a space after `Products `.  Can you provide some more context such as your config and more code where you are trying to use it so I can help?

**Comment by jatniel** [comment]
Thank you very much for your reply

I have taken the instructions: [installation](https://github.com/TappNetwork/laravel-airtable#installation)
.env configured etc
In the controller I have this code: 

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Tapp\Airtable\Airtable;


class SupplierController extends Controller
{

    public function index()
    {

        return view('supplier', [
            'products' => Airtable::table('Products')->get();
        ]);
    }

}
```
Thank you for your help

**Comment by swilla** [comment]
It looks like you are importing the wrong class for `Airtable`.  You can see the facade is aliased here: 
https://github.com/TappNetwork/laravel-airtable/blob/master/composer.json#L53

You can use `use Airtable;` since auto-discovery is set up for this package and it should resolve it appropriately.

**Comment by swilla** [comment]
Let me know if this is still an issue, closing for now.
