### ISSUE TITLE
Using multiple bases

### ISSUE THREAD

**Issue by neodisco** [TappNetwork/laravel-airtable#50]
Just wondering how to configure for using multiple bases. I see in AirtableManager line 113 there is:

`$base = $this->app['config']['airtable.base'];
`

Does this suggests that this library will only ever work with a single base, or have I misunderstood how to specify different bases?

**Comment by chrisvaughan83** [comment]
I just created a pull request for this feature.  it's a super minimal code change.

**Comment by swilla** [comment]
This is merged and tagged: 
https://github.com/TappNetwork/laravel-airtable/releases/tag/v1.1
