### ISSUE TITLE
Issue when AirtableManager tries to create a AirtableApiClient

### ISSUE THREAD

**Issue by dsferruzza** [TappNetwork/laravel-airtable#57]
HI!

I tried to update a project that uses this lib from v1.0 to v1.2.
When running my code, I get the following error:

```
 Tapp\Airtable\Api\AirtableApiClient::__construct(): Argument #4 ($client) must be of type ?Illuminate\Support\Facades\Http, string given, called in vendor/tapp/laravel-airtable/src/AirtableManager.php on line 124
```

Reading the related code shows indeed an error:

- 7 arguments are given to the constructor of `AirtableApiClient`: https://github.com/TappNetwork/laravel-airtable/blob/master/src/AirtableManager.php#L124
- but it only has 6 parameters; https://github.com/TappNetwork/laravel-airtable/blob/master/src/Api/AirtableApiClient.php#L23

The error points out a type error because the fourth parameter was removed, which created a shift.
The commit that introduced the issue is here: https://github.com/TappNetwork/laravel-airtable/commit/eb6aac5e8a9e673889552350a254e7d43ff229f9#diff-62e27cda4cce08967fff7c195aadf69244cdf9d7fa61fa322443478f81da5f4fL24

Could you have a look please?

**Comment by swilla** [comment]
@dsferruzza this should be fixed now in the new release. 

https://github.com/TappNetwork/laravel-airtable/releases/tag/v1.3

**Comment by dsferruzza** [comment]
Indeed it seems to work. Thanks!
