### ISSUE TITLE
Date search/match syntax?

### ISSUE THREAD

**Issue by ChrisHardie** [TappNetwork/laravel-airtable#81]
I have not been able to figure out how to perform a search using an exact match for a date field, e.g. 

`Airtable::findOrCreate(['Date' => Carbon::now()->format('Y-m-d')], [ ... ]);`

will not match on a existing record with a `Date` value of today. I've been working around this by using searches for values within a date range, but that's pretty clunky:

```
        $existingRecords = Airtable::where('Date', '>=', $dayBefore->format('Y-m-d'))
            ->where('Date', '<=', $dayAfter->format('Y-m-d'))
```

Maybe I'm just getting the syntax wrong? Or is this a limitation of the API?

**Comment by swilla** [comment]
@ChrisHardie it's probably possible to match the format that Airtable is expecting. Do you how an example of a date column value that comes back from the API in the raw JSON string?

**Comment by ChrisHardie** [comment]
I think I figured it out after spending more time with the [formula field reference](https://support.airtable.com/docs/formula-field-reference) and the [API encoder](https://codepen.io/airtable/full/MeXqOg). The proper formula for a date comparison is `IS_SAME({Issue date}, '2024-05-22', 'day')` e.g.

```
https://api.airtable.com/v0/appMyBase/My%20Table?filterByFormula=IS_SAME(%7BIssue+date%7D%2C+'2024-05-22'%2C+'day')
```
